Resto/Models/Boissons.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class Boissons:Section
    {
        public Boissons()
        {
            Nom = "Boissons";
            Produits = new List<Produit>
 {
 new Produit{ Nom = "Coca-cola 33cl", Prix = 2.00},
 new Produit{ Nom = "Orangina 33cl", Prix = 2.00},
 new Produit{ Nom = "Perrier 33cl", Prix = 1.50},
 new Produit{ Nom = "Vittel 1L", Prix = 1.00},
 new Produit{ Nom = "Leffe Blonde 25cl", Prix = 3.20},
 new Produit{ Nom = "Leffe Ruby 25cl", Prix = 3.20},
 };
        }
    }
}

Resto/Models/Carte.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class Carte
    {
        public List<Section> Sections { get; set; }

        public Carte()
        {
            Sections = new List<Section>
            {
                new Entrees(),
                new Plats(),
                new Desserts(),
                new Boissons() 
            };
        }
    }
}

Resto/Models/Desserts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class Desserts:Section
    {
        public Desserts()
        {
            Nom = "Desserts";
            Produits = new List<Produit>
 {
 new Produit{ Nom = "Mousse au chocolat façon Grand-mère", Prix = 4.15},
 new Produit{ Nom = "Banana Splite", Prix = 5.00},
 new Produit{ Nom = "Coupe glâcée", Prix = 5.50},
 new Produit{ Nom = "Café gourmand", Prix = 7.50},
 new Produit{ Nom = "Farandole de desserts", Prix = 9.20},
 };
        }
    }
}

Resto/Models/Entrees.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class Entrees : Section
    {

        public Entrees()
        {
            Nom = "Entrées";
            Produits = new List<Produit>
            {
                new Produit{Nom = "Carpaccio de boeuf", Prix = 11.20},
                new Produit{Nom = "Tartare de boeuf", Prix = 12.50},
                new Produit{Nom="Raviolles au gorgonzola", Prix=7.50},
                new Produit{Nom = "Petite salade césar", Prix = 5.20}
            };
        }
    }
}

Resto/Models/Plats.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class Plats : Section
    {
        public Plats()
        {
            Nom = "Plats";
            Produits = new List<Produit>
 {
 new Produit{ Nom = "Penne aux cambas", Prix = 12.50},
 new Produit{ Nom = "Pizza Capriosa", Prix = 14.00},
 new Produit{ Nom = "Pièce du boucher", Prix = 17.50},
 new Produit{ Nom = "Grande salade César", Prix = 8.20},
 new Produit{ Nom = "Pavé de Saumon à la provencale", Prix = 15.20},
 };
        }
    }
}

Resto/Models/Produit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class Produit
    {
        public string Nom { get; set; }
        public double Prix { get; set; }

        public Produit(){ }
    }
}

Resto/Models/Section.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class Section
    {
        public string Nom { get; set; }
        public List<Produit> Produits { get; set; }

        public Section(){ }

        
    }
}

Resto/Models/SectionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class SectionViewModel
    {
        public SectionViewModel()
        {
        }

        

        public List<Section> Sections { get; set; }
    }
}

Resto/Controllers/CarteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Resto.Models;

namespace Resto.Controllers
{
    public class CarteController : Controller
    {
        Carte carte = new Carte();
        // GET: Carte
        public ActionResult Index()
        {
            var model = new SectionViewModel
            {
                Sections = carte.Sections
            };

            return View(model);
        }
    }
}

Resto/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Resto.Models;

namespace Resto.Controllers
{
    public class HomeController : Controller
    {
        Carte carte = new Carte();
        // GET: Home
        public ActionResult Index()
        {
            var model = new SectionViewModel
            {
                Sections = carte.Sections
            };

            return View(model);
          
        }
    }
}

Resto/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Resto.Controllers
{
    public class PageController : Controller
    {
        // GET: Page
        public ActionResult Restaurant()
        {
            return View();
        }
    }
}

Resto/Views/Carte/Index.cshtml
@model Resto.Models.SectionViewModel

<h1>La Carte</h1>
<br/>
@foreach (var lesSections in Model.Sections)
{
    <h2>@lesSections.Nom</h2>
    <br/>
    foreach (var produit in lesSections.Produits)
    {
        <li>@produit.Nom .............. @produit.Prix €</li>
    }
    <br/>
}

Resto/Views/Home/Index.cshtml
@model Resto.Models.SectionViewModel

<h2>Nos Sections</h2>

@foreach (var item in Model.Sections)
            {
<div class="col">
    <div class="card">
        <div class="card-header"><h2>@item.Nom</h2></div>
    </div>
</div>
            }

Resto/Views/Page/Restaurant.cshtml
@{
    ViewBag.Title = "Restaurant";
}

<h2>Restaurant</h2>

Resto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon resto c'est pas l'McDo</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar">
        <div class="container">
            <div class="navbar-header">
                <div class= "flex-md-fill">
                    @Html.ActionLink("Index", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Le Restaurant", "Restaurant", "Page", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("La Carte", "Index", "Carte", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                
                
               
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - El Super Resto</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>